### ISSUE TITLE
Can Neutral Animals get compat with friends and foes mobs?

### ISSUE THREAD

**Issue by Kloytz** [realSmushyTaco/Neutral-Animals#10]
Will there ever be compat with friends and foes?

**Comment by SmushyTaco** [comment]
Do the mods crash when ran together? If they do provide a crash log. If this is a feature request then specify what exactly you're asking for. Thanks.

**Comment by Kloytz** [comment]
mods do not crash together, what I meant is like a compat for the copper golem from friends and foes to attack you also.

**Comment by SmushyTaco** [comment]
That's not planned

**Comment by Kloytz** [comment]
Yeah, asked if a compat for the mobs added from friends and foes will release someday.

**Comment by Kloytz** [comment]
Thanks anyways! Like your mods!
