### ISSUE TITLE
Fatal Error when Combined with Data Attributes mod

### ISSUE THREAD

**Issue by Jurklein** [realSmushyTaco/Neutral-Animals#2]
Tried Minecraft 1.17.1 with fabric modloader v0.11.7; mods:

- dataattributes-1.0.6
- neutral-animals-1.1.0
- fabric-language-kotlin-1.6.5+kotlin.1.5.31
- cloth-config-5.1.40-fabric
- fabric-api-0.42.+1.17

The aforementioned mod's purpose is to "overhaul Minecraft's entity attribute system to be more dynamic and to include follow on attributes (something found in many other games); and expose entity attributes to a datapack system - allowing servers/pack makers to customise every aspect of the entity attribute system".

Neutral_Animals + Data_Attributes combination is fatal. When a passive mob is about to inflict the counter-attack after a player's initial aggression, the game crashes with the following error:
...
java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
...

Full log:
[dataattributes+neutralanimals_crash.log](https://github.com/SmushyTaco/Neutral-Animals/files/7535003/dataattributes%2Bneutralanimals_crash.log)

**Comment by CleverNucleus** [comment]
Hi there,
Upon further testing I've realised that the merge has not in fact fixed the compatibility issue between Data Attributes and Neutral Animals, although I don't understand why yet (issue with multiple RETURN mixins not compounding properly?). Completely my bad, I'll look for other fixes.
