### ISSUE TITLE
[Suggestion] make mobs more aware as well

### ISSUE THREAD

**Issue by Yum-Muy** [realSmushyTaco/Neutral-Animals#9]
I've always wanted a mod that made mobs in general just more... aware, and I think this could be a great addition to this mod. Like for example, say you were to shoot but miss an arrow at a cow(s), it (and the rest, if there are more) would instantly start running away as soon as it heard it.

**Comment by SmushyTaco** [comment]
This is a cool suggestion but won't be implemented.
